In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Data Preprocessing

In [2]:
dataset=pd.read_csv('Churn_Modelling.csv')
print(dataset.shape)
dataset.head()

(10000, 14)


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X=dataset.iloc[:, 3:13].values
y=dataset.iloc[:,13].values

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y.shape

(10000,)

In [6]:
#encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelEncoder_X_1=LabelEncoder()
X[:,1]=labelEncoder_X_1.fit_transform(X[:,1]) #Country
labelEncoder_X_2=LabelEncoder()
X[:,2]=labelEncoder_X_2.fit_transform(X[:,2]) #Gender

In [7]:
X[0:2, :]

array([[619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58]], dtype=object)

In [8]:
from sklearn.compose import ColumnTransformer #The country variable must be dummified using one hot encoder
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(), [1])],    # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                         # Leave the rest of the columns untouched
)
X = np.array(ct.fit_transform(X), dtype=np.float)

In [9]:
X[0,:]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       0.0000000e+00, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [10]:
X=X[:, 1:] #Out of the three variables created for country, after one hot encoding, remove 1 of them due to dummy variable trap

In [11]:
X[0,:]

array([0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [12]:
y.shape

(10000,)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)


(8000, 11) (2000, 11) (8000,) (2000,)


In [14]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [15]:
X_train

array([[-0.57523331, -0.57253893, -0.79241473, ...,  0.63929548,
        -1.030206  ,  1.42600543],
       [-0.57523331, -0.57253893, -0.30630959, ..., -1.56422191,
        -1.030206  , -1.05462873],
       [ 1.73842505, -0.57253893,  1.04857921, ...,  0.63929548,
        -1.030206  , -1.46151672],
       ...,
       [-0.57523331, -0.57253893, -0.33733757, ...,  0.63929548,
        -1.030206  , -0.80185224],
       [-0.57523331, -0.57253893,  0.00397029, ..., -1.56422191,
        -1.030206  ,  0.97184149],
       [ 1.73842505, -0.57253893, -0.57521881, ..., -1.56422191,
        -1.030206  , -1.00400943]])

# Apply ANN

In [16]:
#installing keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [20]:
#initialize ANN
classifier=Sequential()
#Adding input layer and first hidden layer
classifier.add(Dense(output_dim=6, init='uniform', activation='relu', input_dim=11)) #Relu is for Rectifier function, init (uniform) is to assign the weights uniformly near to 0
#Adding the second hidden layer
classifier.add(Dense(output_dim=6, init='uniform', activation='relu'))
#Adding the output layer
classifier.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [26]:
classifier.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 6)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [27]:
#compile ann
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy']) #loss ust be category_crossentropy if three categories are there in output

In [29]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 6s 741us/step - loss: 0.4869 - accuracy: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 184us/step - loss: 0.4296 - accuracy: 0.7962
Epoch 3/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.4247 - accuracy: 0.7962
Epoch 4/100
8000/8000 [==============================] - 1s 179us/step - loss: 0.4201 - accuracy: 0.8119
Epoch 5/100
8000/8000 [==============================] - 2s 228us/step - loss: 0.4174 - accuracy: 0.8246
Epoch 6/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.4149 - accuracy: 0.8286
Epoch 7/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.4131 - accuracy: 0.8319
Epoch 8/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.4122 - accuracy: 0.8320
Epoch 9/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.4109 - accuracy: 0.8329
Epoch 10/100
8000/8000 [==============================]

In [30]:
y_test_preds=classifier.predict(X_test)

In [33]:
#find prob for predicted probability
y_test_preds=(y_test_preds>0.5)
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test, y_test_preds)

array([[1535,   58],
       [ 272,  135]], dtype=int64)

In [35]:
print(classification_report(y_test, y_test_preds))

              precision    recall  f1-score   support

           0       0.85      0.96      0.90      1593
           1       0.70      0.33      0.45       407

    accuracy                           0.83      2000
   macro avg       0.77      0.65      0.68      2000
weighted avg       0.82      0.83      0.81      2000

